// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import { defineConfig } from 'prisma/config';

type Environment = 'development' | 'production' | 'test';

const NODE_ENV = (process.env.NODE_ENV as Environment) ?? 'development';

const envFileMap: Record<Environment, string> = {
	development: '.env.local',
	test: '.env.test',
	production: '.env.production',
};

const envFile = envFileMap[NODE_ENV];

dotenv.config({ path: envFile });

export default defineConfig({
	schema: 'prisma',
	migrations: {
		path: 'prisma/migrations',
	},
	datasource: {
		url: process.env.DATABASE_URL,
	},
});
